version: '3'
services:
  app:
    build: .
    entrypoint: /bin/bash
    stdin_open: true
    tty: true 
    working_dir: /repo
    volumes:
       - /Users/givip/JoyLabs/git_tests:/repo
    environment:
     # GITHUB_TOKEN: ${{ secrets.JEREMY_REPO_TAG_SCOPE_ACCESS_TOKEN }}
      VERBOSE: false
      DRY_RUN: true
      GIT_API_TAGGING: false
      GITHUB_WORKSPACE: /repo
      GITHUB_OUTPUT: /github_output_log

     #develop config
      RELEASE_BRANCHES: master
      DEFAULT_BRANCH: master
      WITH_V: true
      DEFAULT_BUMP: none
      BUILD_NUMBER: true
      INITIAL_BUILD_NUMDER: 0
      TAG_CONTEXT: branch
      PRERELEASE: true
      PRERELEASE_SUFFIX: dev

    #release config
      # RELEASE_BRANCHES: master
      # DEFAULT_BRANCH: master
      # WITH_V: true
      # DEFAULT_BUMP: none
      # BUILD_NUMBER: true
      # INITIAL_BUILD_NUMDER: 0
      # TAG_CONTEXT: repo
      # PRERELEASE: true
      # PRERELEASE_SUFFIX: rc

    #hotfix config
      # RELEASE_BRANCHES: master
      # DEFAULT_BRANCH: master
      # WITH_V: true
      # DEFAULT_BUMP: none
      # BUILD_NUMBER: true
      # INITIAL_BUILD_NUMDER: 0
      # TAG_CONTEXT: repo
      # PRERELEASE: true
      # PRERELEASE_SUFFIX: hotfix

    # #master config
      # RELEASE_BRANCHES: master
      # DEFAULT_BRANCH: master
      # WITH_V: true
      # DEFAULT_BUMP: none
      # BUILD_NUMBER: true
      # INITIAL_BUILD_NUMDER: 0
      # TAG_CONTEXT: branch
      
